### ISSUE TITLE
Rogue DROP TABLE line 45 init.sql

### ISSUE THREAD

**Issue by Tiarama** [fac21/Week6--Web-App--EMNS#29]
Is there a reason why on of your drop table commands is on line 45 and the rest are at the top?
It will definitely still work!
It's just I'm not sure, but I feel like it might(?) be more readable to either have them all on one line, or all split up respectively.
I think Oli did it your way, but I'd like to know if you have any reasoning behind it? :)

**Comment by oliverjam** [comment]
The reason I did them on separate lines in the sessions-auth workshop is because I started out using SQLite (not Postgres) and that doesn't support dropping multiple tables in one statement 🙃 

I can't think of any reason to prefer one over the other generally.

**Comment by michael-devlin** [comment]
See Oli's comment.
