### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by rosie-ollerenshaw** [fac21/Week6--Web-App--EMNS#30]
https://github.com/fac21/Week6--Web-App--EMNS/blob/38924355dc8b1fcb2fdcc2cc73f96208a4869c53/database/model.js#L1

We're interested in what you're doing here - why did you choose to put the variable in an object here?
We also noticed that you don't use the variable in the file, did it get moved somewhere else? :)

**Comment by oliverjam** [comment]
(this looks like a rogue VS Code auto-import to me)

**Comment by michael-devlin** [comment]
See Oli's comment
