### ISSUE TITLE
COMPLIMENT - cascade delete

### ISSUE THREAD

**Issue by rosie-ollerenshaw** [fac21/Week6--Web-App--EMNS#31]
https://github.com/fac21/Week6--Web-App--EMNS/blob/38924355dc8b1fcb2fdcc2cc73f96208a4869c53/database/init.sql#L20

this is really cool!!!! we love this - where did you find out about it? well done! :D

**Comment by michael-devlin** [comment]
From the previous workshop (last week). Maybe the 'Database Testing' workshop... not sure though.
